name: uber_eats_restaurant
description: "Flutter Uber Eats restaurant"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sizer: ^3.0.5
  country_picker: ^2.0.27
  font_awesome_flutter: ^10.8.0
  pin_code_fields: ^8.0.1
  persistent_bottom_nav_bar_v2: ^5.3.1
  page_transition: ^2.2.1
  provider: ^6.1.5
  http: ^1.3.0
  image_picker: ^1.1.2
  uuid: ^4.5.1
  carousel_slider: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/categories/
    - assets/images/splash_screen/
  fonts:
    - family: UberMoveMedium
      fonts:
        - asset: assets/fonts/UberMoveMedium.otf
    - family: UberMoveBold
      fonts:
        - asset: assets/fonts/UberMoveBold.otf